---
name: Update a Product
description: Update information about a product in the database
title: "[Product Update]: <vendor> - <product>"
body:
  - type: input
    id: product-vendor
    attributes:
      label: Product vendor
      description: Who is the vendor for the product?
      placeholder: Cisco, Dell, IBM, etc.
    validations:
      required: true
  - type: input
    id: product-name
    attributes:
      label: Product name
      description: What is the name of the product?
      placeholder: AppDynamics, BigFix Inventory, Centera, etc.
    validations:
      required: true
  - type: textarea
    id: update-context
    attributes:
      label: Context
      description: Please provide context around the update.
  - type: input
    id: product-versions
    attributes:
      label: Product version(s)
      description: What version(s) of the product are affected?
  - type: dropdown
    id: product-updated
    attributes:
      label: Product update
      description: Is there an update available for the product?
      options:
        - Available
        - Not Available
  - type: input
    id: product-update-link
    attributes:
      label: Product update link
      description: Where can the update be found, if one is available?
  - type: input
    id: product-last-updated
    attributes:
      label: Last updated
      description: When was the product last updated?
      placeholder: "2021-12-06"
  - type: textarea
    id: product-notes
    attributes:
      label: Notes
  - type: textarea
    id: product-references
    attributes:
      label: References
