---
name: Update the software lists

on:
  push:
    branches:
      - develop

env:
  PIP_CACHE_DIR: ~/.cache/pip
  TESTING_BRANCH_BASE: testing/update_software_lists

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      # Commit author information for git
      git_author: ${{ steps.git-config.outputs.author }}
      git_email: ${{ steps.git-config.outputs.email }}
      git_user: ${{ steps.git-config.outputs.user }}
      # The name of the branch used for testing
      testing_branch: ${{ steps.testing-branch.outputs.name }}
    steps:
      - id: git-config
        run: |
          echo "::set-output name=author::$GIT_USER <$GIT_EMAIL>"
          echo "::set-output name=email::$GIT_EMAIL"
          echo "::set-output name=user::$GIT_USER"
        env:
          GIT_EMAIL: ${{ fromJson(secrets.GIT_AUTHOR_INFORMATION).user.email }}
          GIT_USER: ${{ fromJson(secrets.GIT_AUTHOR_INFORMATION).user.name }}
      - id: testing-branch
        run: echo "::set-output name=name::$BASE_BRANCH/$COMMIT_SHA"
        env:
          BASE_BRANCH: ${{ env.TESTING_BRANCH_BASE }}
          COMMIT_SHA: ${{ github.sha }}
  generate_updates:
    runs-on: ubuntu-latest
    needs: setup
    outputs:
      # If changes are detected then a commit will have been pushed
      has_updates: ${{ steps.commit-for-testing.outputs.changes_detected }}
    # Don't run if we're seeing an update push
    if: github.actor != needs.setup.outputs.git_user
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.CISAGOVBOT_PAT }}
      - id: setup-python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - uses: actions/cache@v3
        env:
          BASE_CACHE_KEY: "${{ github.job }}-${{ runner.os }}-\
            py${{ steps.setup-python.outputs.python-version }}-"
        with:
          path: |
            ${{ env.PIP_CACHE_DIR }}
          key: "${{ env.BASE_CACHE_KEY }}\
            ${{ hashFiles('.github/workflows/update_software_lists.yml') }}-\
            ${{ hashFiles('config/requirements.txt') }}"
          restore-keys: |
            ${{ env.BASE_CACHE_KEY }}
      - name: Update Python base packages
        run: python -m pip install --upgrade pip setuptools wheel
      - name: Install dependencies
        run: pip install --upgrade --requirement config/requirements.txt
      - name: Create the branch for test validation
        run: git switch --create ${{ needs.setup.outputs.testing_branch }}
      - name: Update the YAML and Markdown files as appropriate
        run: config/update_software_lists.sh
      - id: commit-for-testing
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: ${{ needs.setup.outputs.testing_branch }}
          commit_message: Normalize YAML files and update the software lists
          commit_user_name: ${{ needs.setup.outputs.git_user }}
          commit_user_email: ${{ needs.setup.outputs.git_email }}
          commit_author: ${{ needs.setup.outputs.git_author }}
          file_pattern: data/cisagov*.yml software_lists/software_list_*.md
  merge_updates:
    runs-on: ubuntu-latest
    needs:
      - setup
      - generate_updates
    if: needs.generate_updates.outputs.has_updates == 'true'
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.CISAGOVBOT_PAT }}
      - name: Configure git
        run: |
          git config user.name "${{ needs.setup.outputs.git_user }}"
          git config user.email "${{ needs.setup.outputs.git_email }}"
      - uses: lewagon/wait-on-check-action@v1.1.2
        with:
          check-name: lint
          ref: ${{ needs.setup.outputs.testing_branch }}
          repo-token: ${{ github.token }}
      - name: Merge the testing branch
        run: |
          git fetch
          git merge origin/${{ needs.setup.outputs.testing_branch }}
          git push
      - name: Cleanup testing branch
        run: git push --delete origin ${{ needs.setup.outputs.testing_branch }}
